import { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { AppContextProvider } from "@contexts/AppContext";
const font = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
});

import "../styles/global.css"

export const metadata: Metadata = {
  title: "Leadster - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={font.className}>
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
